// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WT32-SC01-PLUS

#include "../ui.h"

void ui_LocationScreen_screen_init(void)
{
    ui_LocationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LocationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgimg2 = lv_img_create(ui_LocationScreen);
    lv_img_set_src(ui_bgimg2, &ui_img_bg3_png);
    lv_obj_set_width(ui_bgimg2, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_bgimg2, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_bgimg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgimg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgimg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bgimg2, 340);

    ui_backbtn1 = lv_img_create(ui_LocationScreen);
    lv_img_set_src(ui_backbtn1, &ui_img_backimg_png);
    lv_obj_set_width(ui_backbtn1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_backbtn1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_backbtn1, -189);
    lv_obj_set_y(ui_backbtn1, 138);
    lv_obj_set_align(ui_backbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LocationDropdown = lv_dropdown_create(ui_LocationScreen);
    lv_dropdown_set_options(ui_LocationDropdown, "Rackeve\nBudapest\nKiskunlachaza");
    lv_obj_set_width(ui_LocationDropdown, 421);
    lv_obj_set_height(ui_LocationDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LocationDropdown, 0);
    lv_obj_set_y(ui_LocationDropdown, -75);
    lv_obj_set_align(ui_LocationDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LocationDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_LocationDropdown, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LocationDropdown, lv_color_hex(0x181C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LocationDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_LocationDropdown), lv_color_hex(0x181C18),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_LocationDropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_LocationDropdown), lv_color_hex(0xDE0000),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_LocationDropdown), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbtn1, ui_event_backbtn1, LV_EVENT_ALL, NULL);

}
