// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WT32-SC01-PLUS

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_bgimg, &ui_img_bg3_png);
    lv_obj_set_width(ui_bgimg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_bgimg, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_bgimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bgimg, 340);

    ui_optionbtn = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_optionbtn, &ui_img_optionsbtn_png);
    lv_obj_set_width(ui_optionbtn, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_optionbtn, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_optionbtn, 209);
    lv_obj_set_y(ui_optionbtn, -136);
    lv_obj_set_align(ui_optionbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_optionbtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_optionbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_optionbtn, 115);

    ui_dummytext = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_dummytext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dummytext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dummytext, 0);
    lv_obj_set_y(ui_dummytext, -58);
    lv_obj_set_align(ui_dummytext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dummytext, "       ");
    lv_obj_set_style_text_letter_space(ui_dummytext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_dummytext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dummytext, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_dummytext, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dummytext, lv_color_hex(0x490A05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dummytext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dummytext, lv_color_hex(0x490A05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dummytext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dummytext, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dummytext, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -91);
    lv_obj_set_y(ui_hour, -58);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "23");
    lv_obj_set_style_text_letter_space(ui_hour, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute, 85);
    lv_obj_set_y(ui_minute, -58);
    lv_obj_set_align(ui_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute, "59");
    lv_obj_set_style_text_letter_space(ui_minute, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_minute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minute, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_locationtext = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_locationtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_locationtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_locationtext, -152);
    lv_obj_set_y(ui_locationtext, -150);
    lv_obj_set_align(ui_locationtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_locationtext, "Rackeve");
    lv_obj_set_style_text_font(ui_locationtext, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_separator = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_separator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_separator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_separator, 0);
    lv_obj_set_y(ui_separator, -61);
    lv_obj_set_align(ui_separator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_separator, ":");
    lv_obj_set_style_text_letter_space(ui_separator, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_separator, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinpointimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_pinpointimg, &ui_img_pinpoint_png);
    lv_obj_set_width(ui_pinpointimg, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_pinpointimg, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_pinpointimg, -206);
    lv_obj_set_y(ui_pinpointimg, -150);
    lv_obj_set_align(ui_pinpointimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinpointimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pinpointimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_pinpointimg, 20);

    ui_weatherinfo = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_weatherinfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherinfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherinfo, 0);
    lv_obj_set_y(ui_weatherinfo, 84);
    lv_obj_set_align(ui_weatherinfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherinfo, "Broken clouds");
    lv_obj_set_style_text_align(ui_weatherinfo, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherinfo, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_weatherinfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weatherinfo, lv_color_hex(0x474113), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherinfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_weatherinfo, lv_color_hex(0x887403), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_weatherinfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_weatherinfo, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_weatherinfo, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clearimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_clearimg, &ui_img_clear_sky_png);
    lv_obj_set_width(ui_clearimg, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_clearimg, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_x(ui_clearimg, 0);
    lv_obj_set_y(ui_clearimg, 25);
    lv_obj_set_align(ui_clearimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clearimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clearimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_clearimg, 350);

    ui_temptext = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_temptext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temptext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temptext, -189);
    lv_obj_set_y(ui_temptext, 130);
    lv_obj_set_align(ui_temptext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temptext, "0.1");
    lv_obj_set_style_text_font(ui_temptext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidtext = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_humidtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidtext, -194);
    lv_obj_set_y(ui_humidtext, 147);
    lv_obj_set_align(ui_humidtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidtext, "71");
    lv_obj_set_style_text_font(ui_humidtext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_celsiustext = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_celsiustext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_celsiustext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_celsiustext, -154);
    lv_obj_set_y(ui_celsiustext, 130);
    lv_obj_set_align(ui_celsiustext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_celsiustext, "°C");
    lv_obj_set_style_text_font(ui_celsiustext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percentagetext = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_percentagetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentagetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentagetext, -154);
    lv_obj_set_y(ui_percentagetext, 147);
    lv_obj_set_align(ui_percentagetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentagetext, "%");
    lv_obj_set_style_text_font(ui_percentagetext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temphumimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_temphumimg, &ui_img_temphum_png);
    lv_obj_set_width(ui_temphumimg, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_temphumimg, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_temphumimg, -224);
    lv_obj_set_y(ui_temphumimg, 137);
    lv_obj_set_align(ui_temphumimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temphumimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temphumimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_temphumimg, 80);

    ui_rainimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_rainimg, &ui_img_rain_png);
    lv_obj_set_width(ui_rainimg, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_rainimg, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_x(ui_rainimg, 0);
    lv_obj_set_y(ui_rainimg, 25);
    lv_obj_set_align(ui_rainimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rainimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rainimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_rainimg, 350);

    ui_thunderstormimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_thunderstormimg, &ui_img_thunderstorm_png);
    lv_obj_set_width(ui_thunderstormimg, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_thunderstormimg, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_thunderstormimg, 0);
    lv_obj_set_y(ui_thunderstormimg, 25);
    lv_obj_set_align(ui_thunderstormimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_thunderstormimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_thunderstormimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_thunderstormimg, 200);

    ui_lightrainimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_lightrainimg, &ui_img_ligth_rain_png);
    lv_obj_set_width(ui_lightrainimg, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_lightrainimg, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_x(ui_lightrainimg, 0);
    lv_obj_set_y(ui_lightrainimg, 25);
    lv_obj_set_align(ui_lightrainimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightrainimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lightrainimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_lightrainimg, 400);

    ui_fogimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_fogimg, &ui_img_fog_png);
    lv_obj_set_width(ui_fogimg, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_fogimg, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_x(ui_fogimg, 0);
    lv_obj_set_y(ui_fogimg, 25);
    lv_obj_set_align(ui_fogimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fogimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fogimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_fogimg, 400);

    ui_snowimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_snowimg, &ui_img_1041181811);
    lv_obj_set_width(ui_snowimg, LV_SIZE_CONTENT);   /// 1200
    lv_obj_set_height(ui_snowimg, LV_SIZE_CONTENT);    /// 1242
    lv_obj_set_x(ui_snowimg, 0);
    lv_obj_set_y(ui_snowimg, 25);
    lv_obj_set_align(ui_snowimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_snowimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_snowimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_snowimg, 90);

    ui_brokencloudsimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_brokencloudsimg, &ui_img_brokencloudsimg_png);
    lv_obj_set_width(ui_brokencloudsimg, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_brokencloudsimg, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_x(ui_brokencloudsimg, 0);
    lv_obj_set_y(ui_brokencloudsimg, 25);
    lv_obj_set_align(ui_brokencloudsimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brokencloudsimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brokencloudsimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_brokencloudsimg, 400);

    ui_wifioffimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_wifioffimg, &ui_img_wifioffimg_png);
    lv_obj_set_width(ui_wifioffimg, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_wifioffimg, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_wifioffimg, 150);
    lv_obj_set_y(ui_wifioffimg, -136);
    lv_obj_set_align(ui_wifioffimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifioffimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifioffimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifioffimg, 80);

    ui_wifionimg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_wifionimg, &ui_img_wifionimg_png);
    lv_obj_set_width(ui_wifionimg, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_wifionimg, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_wifionimg, 150);
    lv_obj_set_y(ui_wifionimg, -136);
    lv_obj_set_align(ui_wifionimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifionimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifionimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifionimg, 80);

    ui_datetext = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_datetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datetext, 163);
    lv_obj_set_y(ui_datetext, 149);
    lv_obj_set_align(ui_datetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datetext, "2024.01.01");
    lv_obj_set_style_text_font(ui_datetext, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_optionbtn, ui_event_optionbtn, LV_EVENT_ALL, NULL);

}
