// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WT32-SC01-PLUS

#include "../ui.h"

void ui_OptionsScreen_screen_init(void)
{
    ui_OptionsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OptionsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgimg3 = lv_img_create(ui_OptionsScreen);
    lv_img_set_src(ui_bgimg3, &ui_img_bg3_png);
    lv_obj_set_width(ui_bgimg3, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_bgimg3, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_bgimg3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgimg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgimg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bgimg3, 340);

    ui_WiFiPanel = lv_obj_create(ui_OptionsScreen);
    lv_obj_set_width(ui_WiFiPanel, 421);
    lv_obj_set_height(ui_WiFiPanel, 29);
    lv_obj_set_x(ui_WiFiPanel, 0);
    lv_obj_set_y(ui_WiFiPanel, -83);
    lv_obj_set_align(ui_WiFiPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WiFiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiOptionsText = lv_label_create(ui_WiFiPanel);
    lv_obj_set_width(ui_WiFiOptionsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiOptionsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiOptionsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiOptionsText, "WiFi");
    lv_obj_set_style_text_font(ui_WiFiOptionsText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LocationPanel = lv_obj_create(ui_OptionsScreen);
    lv_obj_set_width(ui_LocationPanel, 421);
    lv_obj_set_height(ui_LocationPanel, 29);
    lv_obj_set_x(ui_LocationPanel, 0);
    lv_obj_set_y(ui_LocationPanel, -41);
    lv_obj_set_align(ui_LocationPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LocationPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LocationOptionsText = lv_label_create(ui_LocationPanel);
    lv_obj_set_width(ui_LocationOptionsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LocationOptionsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LocationOptionsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LocationOptionsText, "Location");
    lv_obj_set_style_text_font(ui_LocationOptionsText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LocationPanel1 = lv_obj_create(ui_OptionsScreen);
    lv_obj_set_width(ui_LocationPanel1, 421);
    lv_obj_set_height(ui_LocationPanel1, 29);
    lv_obj_set_align(ui_LocationPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LocationPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessAndjustText = lv_label_create(ui_LocationPanel1);
    lv_obj_set_width(ui_BrightnessAndjustText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessAndjustText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessAndjustText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessAndjustText, "Brightness");
    lv_obj_set_style_text_font(ui_BrightnessAndjustText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadioPanel = lv_obj_create(ui_OptionsScreen);
    lv_obj_set_width(ui_RadioPanel, 421);
    lv_obj_set_height(ui_RadioPanel, 29);
    lv_obj_set_x(ui_RadioPanel, 0);
    lv_obj_set_y(ui_RadioPanel, 41);
    lv_obj_set_align(ui_RadioPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RadioPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_radioplayertext = lv_label_create(ui_RadioPanel);
    lv_obj_set_width(ui_radioplayertext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_radioplayertext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_radioplayertext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_radioplayertext, "Radio player");
    lv_obj_set_style_text_font(ui_radioplayertext, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn3 = lv_img_create(ui_OptionsScreen);
    lv_img_set_src(ui_backbtn3, &ui_img_backimg_png);
    lv_obj_set_width(ui_backbtn3, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_backbtn3, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_backbtn3, -189);
    lv_obj_set_y(ui_backbtn3, 138);
    lv_obj_set_align(ui_backbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_WiFiOptionsText, ui_event_WiFiOptionsText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiPanel, ui_event_WiFiPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LocationOptionsText, ui_event_LocationOptionsText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LocationPanel, ui_event_LocationPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnessAndjustText, ui_event_BrightnessAndjustText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LocationPanel1, ui_event_LocationPanel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_radioplayertext, ui_event_radioplayertext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RadioPanel, ui_event_RadioPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backbtn3, ui_event_backbtn3, LV_EVENT_ALL, NULL);

}
