// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WT32-SC01-PLUS

#include "../ui.h"

void ui_RadioScreen_screen_init(void)
{
    ui_RadioScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RadioScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgimg5 = lv_img_create(ui_RadioScreen);
    lv_img_set_src(ui_bgimg5, &ui_img_bg3_png);
    lv_obj_set_width(ui_bgimg5, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_bgimg5, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_bgimg5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgimg5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgimg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bgimg5, 340);

    ui_backbtn5 = lv_img_create(ui_RadioScreen);
    lv_img_set_src(ui_backbtn5, &ui_img_backimg_png);
    lv_obj_set_width(ui_backbtn5, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_backbtn5, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_backbtn5, -189);
    lv_obj_set_y(ui_backbtn5, 138);
    lv_obj_set_align(ui_backbtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volumeslider = lv_slider_create(ui_RadioScreen);
    lv_slider_set_value(ui_volumeslider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_volumeslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_volumeslider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_volumeslider, 400);
    lv_obj_set_height(ui_volumeslider, 20);
    lv_obj_set_align(ui_volumeslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0x730000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0xD80000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_radstationtext = lv_label_create(ui_RadioScreen);
    lv_obj_set_width(ui_radstationtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_radstationtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_radstationtext, 0);
    lv_obj_set_y(ui_radstationtext, -80);
    lv_obj_set_align(ui_radstationtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_radstationtext, "Radionetz");
    lv_obj_set_style_text_font(ui_radstationtext, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playbtn = lv_btn_create(ui_RadioScreen);
    lv_obj_set_width(ui_playbtn, 60);
    lv_obj_set_height(ui_playbtn, 60);
    lv_obj_set_x(ui_playbtn, 0);
    lv_obj_set_y(ui_playbtn, 60);
    lv_obj_set_align(ui_playbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_playbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_playbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_playbtn, lv_color_hex(0x4A0800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_playbtn, &ui_img_playbuttonimg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_playbtn, lv_color_hex(0xDE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_playbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_playbtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_playbtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stopbtn = lv_btn_create(ui_RadioScreen);
    lv_obj_set_width(ui_stopbtn, 60);
    lv_obj_set_height(ui_stopbtn, 60);
    lv_obj_set_x(ui_stopbtn, 0);
    lv_obj_set_y(ui_stopbtn, 60);
    lv_obj_set_align(ui_stopbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stopbtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stopbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_stopbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_stopbtn, lv_color_hex(0x4A0800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stopbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_stopbtn, &ui_img_stopbuttonimg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_stopbtn, lv_color_hex(0xDE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_stopbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_stopbtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_stopbtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_radiostationdropdown = lv_dropdown_create(ui_RadioScreen);
    lv_dropdown_set_options(ui_radiostationdropdown,
                            "Radionetz\nRadio 1\nRetro\nPetofi\nPoptarisznya\nDance Wave\nGalaxis Radio\nMusic Station");
    lv_obj_set_width(ui_radiostationdropdown, 316);
    lv_obj_set_height(ui_radiostationdropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_radiostationdropdown, 0);
    lv_obj_set_y(ui_radiostationdropdown, -70);
    lv_obj_set_align(ui_radiostationdropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_radiostationdropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_radiostationdropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_radiostationdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_radiostationdropdown, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_radiostationdropdown, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_radiostationdropdown, &ui_img_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_radiostationdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_radiostationdropdown, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_radiostationdropdown, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_radiostationdropdown, LV_TEXT_ALIGN_RIGHT, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_radiostationdropdown), LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_radiostationdropdown), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_radiostationdropdown), lv_color_hex(0x181C18),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_radiostationdropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_radiostationdropdown), lv_color_hex(0x730000),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_radiostationdropdown), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbtn5, ui_event_backbtn5, LV_EVENT_ALL, NULL);

}
