// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WT32-SC01-PLUS

#include "../ui.h"

void ui_WiFiScreen_screen_init(void)
{
    ui_WiFiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgimg1 = lv_img_create(ui_WiFiScreen);
    lv_img_set_src(ui_bgimg1, &ui_img_bg3_png);
    lv_obj_set_width(ui_bgimg1, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_bgimg1, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_bgimg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgimg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgimg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bgimg1, 340);

    ui_wifissidarea = lv_textarea_create(ui_WiFiScreen);
    lv_obj_set_width(ui_wifissidarea, 190);
    lv_obj_set_height(ui_wifissidarea, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_wifissidarea, -115);
    lv_obj_set_y(ui_wifissidarea, -43);
    lv_obj_set_align(ui_wifissidarea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifissidarea, "SSID");
    lv_textarea_set_one_line(ui_wifissidarea, true);
    lv_obj_add_flag(ui_wifissidarea, LV_OBJ_FLAG_HIDDEN);     /// Flags



    ui_wifipassarea = lv_textarea_create(ui_WiFiScreen);
    lv_obj_set_width(ui_wifipassarea, 190);
    lv_obj_set_height(ui_wifipassarea, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_wifipassarea, 115);
    lv_obj_set_y(ui_wifipassarea, -43);
    lv_obj_set_align(ui_wifipassarea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifipassarea, "PASSWORD");
    lv_textarea_set_one_line(ui_wifipassarea, true);
    lv_obj_add_flag(ui_wifipassarea, LV_OBJ_FLAG_HIDDEN);     /// Flags



    ui_Panel1 = lv_obj_create(ui_WiFiScreen);
    lv_obj_set_width(ui_Panel1, 421);
    lv_obj_set_height(ui_Panel1, 29);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -83);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiText = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_WiFiText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiText, -176);
    lv_obj_set_y(ui_WiFiText, 0);
    lv_obj_set_align(ui_WiFiText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiText, "WiFi");
    lv_obj_set_style_text_font(ui_WiFiText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifisw = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_Wifisw, 57);
    lv_obj_set_height(ui_Wifisw, 25);
    lv_obj_set_x(ui_Wifisw, 170);
    lv_obj_set_y(ui_Wifisw, -1);
    lv_obj_set_align(ui_Wifisw, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Wifisw, lv_color_hex(0x770202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifisw, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Wifisw, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifisw, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_keyboard = lv_keyboard_create(ui_WiFiScreen);
    lv_obj_set_width(ui_keyboard, 320);
    lv_obj_set_height(ui_keyboard, 130);
    lv_obj_set_x(ui_keyboard, 62);
    lv_obj_set_y(ui_keyboard, 95);
    lv_obj_set_align(ui_keyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_style_bg_color(ui_keyboard, lv_color_hex(0x730000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_backbtn4 = lv_img_create(ui_WiFiScreen);
    lv_img_set_src(ui_backbtn4, &ui_img_backimg_png);
    lv_obj_set_width(ui_backbtn4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_backbtn4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_backbtn4, -189);
    lv_obj_set_y(ui_backbtn4, 138);
    lv_obj_set_align(ui_backbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_handshakebtn = lv_btn_create(ui_WiFiScreen);
    lv_obj_set_width(ui_handshakebtn, 40);
    lv_obj_set_height(ui_handshakebtn, 40);
    lv_obj_set_x(ui_handshakebtn, 207);
    lv_obj_set_y(ui_handshakebtn, -136);
    lv_obj_set_align(ui_handshakebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_handshakebtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_handshakebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_handshakebtn, lv_color_hex(0x730000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_handshakebtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_handshakebtn, &ui_img_wifi_handshakeimg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifionoptimg = lv_img_create(ui_WiFiScreen);
    lv_img_set_src(ui_wifionoptimg, &ui_img_wifionimg_png);
    lv_obj_set_width(ui_wifionoptimg, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_wifionoptimg, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_wifionoptimg, 150);
    lv_obj_set_y(ui_wifionoptimg, -136);
    lv_obj_set_align(ui_wifionoptimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifionoptimg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifionoptimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifionoptimg, 80);

    ui_wifistatustext = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_wifistatustext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistatustext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifistatustext, 0);
    lv_obj_set_y(ui_wifistatustext, -150);
    lv_obj_set_align(ui_wifistatustext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifistatustext, "Connected!");
    lv_obj_add_flag(ui_wifistatustext, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_keyboard_set_textarea(ui_keyboard, ui_wifissidarea);
    lv_obj_add_event_cb(ui_backbtn4, ui_event_backbtn4, LV_EVENT_ALL, NULL);

}
