// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WT32-SC01-PLUS

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_bgimg;
void ui_event_optionbtn(lv_event_t * e);
lv_obj_t * ui_optionbtn;
lv_obj_t * ui_dummytext;
lv_obj_t * ui_hour;
lv_obj_t * ui_minute;
lv_obj_t * ui_locationtext;
lv_obj_t * ui_separator;
lv_obj_t * ui_pinpointimg;
lv_obj_t * ui_weatherinfo;
lv_obj_t * ui_clearimg;
lv_obj_t * ui_temptext;
lv_obj_t * ui_humidtext;
lv_obj_t * ui_celsiustext;
lv_obj_t * ui_percentagetext;
lv_obj_t * ui_temphumimg;
lv_obj_t * ui_rainimg;
lv_obj_t * ui_thunderstormimg;
lv_obj_t * ui_lightrainimg;
lv_obj_t * ui_fogimg;
lv_obj_t * ui_snowimg;
lv_obj_t * ui_brokencloudsimg;
lv_obj_t * ui_wifioffimg;
lv_obj_t * ui_wifionimg;
lv_obj_t * ui_datetext;


// SCREEN: ui_OptionsScreen
void ui_OptionsScreen_screen_init(void);
lv_obj_t * ui_OptionsScreen;
lv_obj_t * ui_bgimg3;
void ui_event_WiFiPanel(lv_event_t * e);
lv_obj_t * ui_WiFiPanel;
void ui_event_WiFiOptionsText(lv_event_t * e);
lv_obj_t * ui_WiFiOptionsText;
void ui_event_LocationPanel(lv_event_t * e);
lv_obj_t * ui_LocationPanel;
void ui_event_LocationOptionsText(lv_event_t * e);
lv_obj_t * ui_LocationOptionsText;
void ui_event_LocationPanel1(lv_event_t * e);
lv_obj_t * ui_LocationPanel1;
void ui_event_BrightnessAndjustText(lv_event_t * e);
lv_obj_t * ui_BrightnessAndjustText;
void ui_event_RadioPanel(lv_event_t * e);
lv_obj_t * ui_RadioPanel;
void ui_event_radioplayertext(lv_event_t * e);
lv_obj_t * ui_radioplayertext;
void ui_event_backbtn3(lv_event_t * e);
lv_obj_t * ui_backbtn3;


// SCREEN: ui_WiFiScreen
void ui_WiFiScreen_screen_init(void);
lv_obj_t * ui_WiFiScreen;
lv_obj_t * ui_bgimg1;
lv_obj_t * ui_wifissidarea;
lv_obj_t * ui_wifipassarea;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_WiFiText;
lv_obj_t * ui_Wifisw;
lv_obj_t * ui_keyboard;
void ui_event_backbtn4(lv_event_t * e);
lv_obj_t * ui_backbtn4;
lv_obj_t * ui_handshakebtn;
lv_obj_t * ui_wifionoptimg;
lv_obj_t * ui_wifistatustext;


// SCREEN: ui_LocationScreen
void ui_LocationScreen_screen_init(void);
lv_obj_t * ui_LocationScreen;
lv_obj_t * ui_bgimg2;
void ui_event_backbtn1(lv_event_t * e);
lv_obj_t * ui_backbtn1;
lv_obj_t * ui_LocationDropdown;


// SCREEN: ui_BrightnessScreen
void ui_BrightnessScreen_screen_init(void);
lv_obj_t * ui_BrightnessScreen;
lv_obj_t * ui_bgimg4;
void ui_event_backbtn2(lv_event_t * e);
lv_obj_t * ui_backbtn2;
lv_obj_t * ui_brightnessslider;
lv_obj_t * ui_BrightnessText;
lv_obj_t * ui_percentagetext1;


// SCREEN: ui_RadioScreen
void ui_RadioScreen_screen_init(void);
lv_obj_t * ui_RadioScreen;
lv_obj_t * ui_bgimg5;
void ui_event_backbtn5(lv_event_t * e);
lv_obj_t * ui_backbtn5;
lv_obj_t * ui_volumeslider;
lv_obj_t * ui_radstationtext;
lv_obj_t * ui_playbtn;
lv_obj_t * ui_stopbtn;
lv_obj_t * ui_radiostationdropdown;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_bg[1] = {&ui_img_bg3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_optionbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_OptionsScreen_screen_init);
    }
}
void ui_event_WiFiPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_WiFiScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_WiFiScreen_screen_init);
    }
}
void ui_event_WiFiOptionsText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_WiFiScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_WiFiScreen_screen_init);
    }
}
void ui_event_LocationPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_LocationScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_LocationScreen_screen_init);
    }
}
void ui_event_LocationOptionsText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_LocationScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_LocationScreen_screen_init);
    }
}
void ui_event_LocationPanel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_BrightnessScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_BrightnessScreen_screen_init);
    }
}
void ui_event_BrightnessAndjustText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_BrightnessScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_BrightnessScreen_screen_init);
    }
}
void ui_event_RadioPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RadioScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_RadioScreen_screen_init);
    }
}
void ui_event_radioplayertext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_RadioScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_RadioScreen_screen_init);
    }
}
void ui_event_backbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_backbtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OptionsScreen_screen_init);
        _ui_flag_modify(ui_keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifipassarea, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifissidarea, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_handshakebtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifistatustext, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_backbtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OptionsScreen_screen_init);
    }
}
void ui_event_backbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OptionsScreen_screen_init);
    }
}
void ui_event_backbtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OptionsScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_OptionsScreen_screen_init();
    ui_WiFiScreen_screen_init();
    ui_LocationScreen_screen_init();
    ui_BrightnessScreen_screen_init();
    ui_RadioScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
