// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WT32-SC01-PLUS

#ifndef _WT32_SC01_PLUS_UI_H
#define _WT32_SC01_PLUS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_bgimg;
void ui_event_optionbtn(lv_event_t * e);
extern lv_obj_t * ui_optionbtn;
extern lv_obj_t * ui_dummytext;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_minute;
extern lv_obj_t * ui_locationtext;
extern lv_obj_t * ui_separator;
extern lv_obj_t * ui_pinpointimg;
extern lv_obj_t * ui_weatherinfo;
extern lv_obj_t * ui_clearimg;
extern lv_obj_t * ui_temptext;
extern lv_obj_t * ui_humidtext;
extern lv_obj_t * ui_celsiustext;
extern lv_obj_t * ui_percentagetext;
extern lv_obj_t * ui_temphumimg;
extern lv_obj_t * ui_rainimg;
extern lv_obj_t * ui_thunderstormimg;
extern lv_obj_t * ui_lightrainimg;
extern lv_obj_t * ui_fogimg;
extern lv_obj_t * ui_snowimg;
extern lv_obj_t * ui_brokencloudsimg;
extern lv_obj_t * ui_wifioffimg;
extern lv_obj_t * ui_wifionimg;
extern lv_obj_t * ui_datetext;
// SCREEN: ui_OptionsScreen
void ui_OptionsScreen_screen_init(void);
extern lv_obj_t * ui_OptionsScreen;
extern lv_obj_t * ui_bgimg3;
void ui_event_WiFiPanel(lv_event_t * e);
extern lv_obj_t * ui_WiFiPanel;
void ui_event_WiFiOptionsText(lv_event_t * e);
extern lv_obj_t * ui_WiFiOptionsText;
void ui_event_LocationPanel(lv_event_t * e);
extern lv_obj_t * ui_LocationPanel;
void ui_event_LocationOptionsText(lv_event_t * e);
extern lv_obj_t * ui_LocationOptionsText;
void ui_event_LocationPanel1(lv_event_t * e);
extern lv_obj_t * ui_LocationPanel1;
void ui_event_BrightnessAndjustText(lv_event_t * e);
extern lv_obj_t * ui_BrightnessAndjustText;
void ui_event_RadioPanel(lv_event_t * e);
extern lv_obj_t * ui_RadioPanel;
void ui_event_radioplayertext(lv_event_t * e);
extern lv_obj_t * ui_radioplayertext;
void ui_event_backbtn3(lv_event_t * e);
extern lv_obj_t * ui_backbtn3;
// SCREEN: ui_WiFiScreen
void ui_WiFiScreen_screen_init(void);
extern lv_obj_t * ui_WiFiScreen;
extern lv_obj_t * ui_bgimg1;
extern lv_obj_t * ui_wifissidarea;
extern lv_obj_t * ui_wifipassarea;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_WiFiText;
extern lv_obj_t * ui_Wifisw;
extern lv_obj_t * ui_keyboard;
void ui_event_backbtn4(lv_event_t * e);
extern lv_obj_t * ui_backbtn4;
extern lv_obj_t * ui_handshakebtn;
extern lv_obj_t * ui_wifionoptimg;
extern lv_obj_t * ui_wifistatustext;
// SCREEN: ui_LocationScreen
void ui_LocationScreen_screen_init(void);
extern lv_obj_t * ui_LocationScreen;
extern lv_obj_t * ui_bgimg2;
void ui_event_backbtn1(lv_event_t * e);
extern lv_obj_t * ui_backbtn1;
extern lv_obj_t * ui_LocationDropdown;
// SCREEN: ui_BrightnessScreen
void ui_BrightnessScreen_screen_init(void);
extern lv_obj_t * ui_BrightnessScreen;
extern lv_obj_t * ui_bgimg4;
void ui_event_backbtn2(lv_event_t * e);
extern lv_obj_t * ui_backbtn2;
extern lv_obj_t * ui_brightnessslider;
extern lv_obj_t * ui_BrightnessText;
extern lv_obj_t * ui_percentagetext1;
extern lv_obj_t * ui_brrollerfrom;
extern lv_obj_t * ui_dimscreentext;
extern lv_obj_t * ui_brrollerto;
extern lv_obj_t * ui_dimscreentext2;
// SCREEN: ui_RadioScreen
void ui_RadioScreen_screen_init(void);
extern lv_obj_t * ui_RadioScreen;
extern lv_obj_t * ui_bgimg5;
void ui_event_backbtn5(lv_event_t * e);
extern lv_obj_t * ui_backbtn5;
extern lv_obj_t * ui_volumeslider;
extern lv_obj_t * ui_radstationtext;
extern lv_obj_t * ui_playbtn;
extern lv_obj_t * ui_stopbtn;
extern lv_obj_t * ui_radiostationdropdown;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bg3_png);    // assets\bg3.png
LV_IMG_DECLARE(ui_img_optionsbtn_png);    // assets\optionsbtn.png
LV_IMG_DECLARE(ui_img_pinpoint_png);    // assets\pinpoint.png
LV_IMG_DECLARE(ui_img_clear_sky_png);    // assets\clear_sky.png
LV_IMG_DECLARE(ui_img_temphum_png);    // assets\temphum.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets\rain.png
LV_IMG_DECLARE(ui_img_thunderstorm_png);    // assets\thunderstorm.png
LV_IMG_DECLARE(ui_img_ligth_rain_png);    // assets\ligth_rain.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets\fog.png
LV_IMG_DECLARE(ui_img_1041181811);    // assets\1200px-Snow_flake.svg.png
LV_IMG_DECLARE(ui_img_brokencloudsimg_png);    // assets\brokencloudsimg.png
LV_IMG_DECLARE(ui_img_wifioffimg_png);    // assets\wifioffimg.png
LV_IMG_DECLARE(ui_img_wifionimg_png);    // assets\wifionimg.png
LV_IMG_DECLARE(ui_img_backimg_png);    // assets\backimg.png
LV_IMG_DECLARE(ui_img_wifi_handshakeimg_png);    // assets\wifi_handshakeimg.png
LV_IMG_DECLARE(ui_img_playbuttonimg_png);    // assets\playbuttonimg.png
LV_IMG_DECLARE(ui_img_stopbuttonimg_png);    // assets\stopbuttonimg.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
